# ~~~~~~~~~~~~~~~ LOGIN & STARTUP ~~~~~~~~~~~~~~~

start-at-login = true
after-login-command = []
after-startup-command = []

# ~~~~~~~~~~~~~~~ LAYOUT SETTINGS ~~~~~~~~~~~~~~~

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# ~~~~~~~~~~~~~~~ GAPS ~~~~~~~~~~~~~~~

[gaps]
inner.horizontal = 2
inner.vertical = 2
outer.left = 2
outer.right = 2
outer.top = 2
outer.bottom = 2

# ~~~~~~~~~~~~~~~ KEY LAYOUT ~~~~~~~~~~~~~~~

[key-mapping]
preset = 'qwerty'

# ~~~~~~~~~~~~~~~ KEYBINDINGS ~~~~~~~~~~~~~~~

[mode.main.binding]

# Layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# Focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Resize
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

# Workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-q = 'workspace Q'
alt-w = 'workspace W'
alt-e = 'workspace E'
alt-a = 'workspace A'
alt-s = 'workspace S'
alt-d = 'workspace D'
alt-f = 'workspace F'
alt-z = 'workspace Z'
alt-x = 'workspace X'
alt-c = 'workspace C'

# Move to Workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-q = 'move-node-to-workspace Q'
alt-shift-w = 'move-node-to-workspace W'
alt-shift-e = 'move-node-to-workspace E'
alt-shift-a = 'move-node-to-workspace A'
alt-shift-s = 'move-node-to-workspace S'
alt-shift-d = 'move-node-to-workspace D'
alt-shift-f = 'move-node-to-workspace F'
alt-shift-z = 'move-node-to-workspace Z'
alt-shift-x = 'move-node-to-workspace X'
alt-shift-c = 'move-node-to-workspace C'

# Workspace Navigation
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Mode
alt-shift-semicolon = 'mode service'
